development:
  adapter: mysql2
  encoding: utf8
  reconnect: false
  database: development
  username: root
  password: 
  socket: /tmp/mysql.sock 
test:
  adapter: mysql2
  encoding: utf8
  reconnect: false
  database: test

  username: root
  password: 
  socket: /tmp/mysql.sock 

production:
  adapter: mysql2
  encoding: utf8
  reconnect: false
  database: production

  username: root
  password: qaz2wsx
  socket: /tmp/mysql.sock 