development:
  adapter: postgresql
  encoding: unicode
  reconnect: false
  database: development
  username: postgres
  password: 


test:
  adapter: postgresql
  encoding: unicode
  reconnect: false
  database: test

  username: postgres
  password: 


production:
  adapter: postgresql
  encoding: unicode
  reconnect: false
  database: production

  username: rails
  password: e42f9f6a523ac833f662b11b06d41b30
